database:
  host: "127.0.0.1"
  port: 5432
  user: "keycloak"
  password: "sf2025~SHENMA"
  dbname: "quota_manager"
  sslmode: "disable"

auth_database:
  host: "127.0.0.1"
  port: 5432
  user: "keycloak"
  password: "sf2025~SHENMA"
  dbname: "auth"
  sslmode: "disable"

aigateway:
  host: "127.0.0.1"
  port: 8002
  admin_path: "/v1/chat/completions"
  auth_header: "x-admin-key"
  auth_value: "12345678"
  credential: "credential3"

server:
  port: 8099
  mode: "debug"
  token_header: "authorization"

scheduler:
  scan_interval: "0 0 * * * *" # Scan every hour

voucher:
  signing_key: "your-secret-signing-key-at-least-32-bytes-long-for-security"